model_pairs = [{'alligened':'meta-llama/Llama-2-7b-chat-hf', 'target_model':['meta-llama/Llama-2-7b-hf', 'hfl/chinese-alpaca-2-7b', 
                                                                              'lmsys/vicuna-7b-v1.5',
                                                                              'allenai/tulu-2-7b', 'allenai/tulu-2-dpo-7b']}, 
               {'alligened':'meta-llama/Llama-2-13b-chat-hf', 'target_model':['meta-llama/Llama-2-13b-hf', 'hfl/chinese-alpaca-2-13b', 
                                                                               'NousResearch/Redmond-Puffin-13B', 'WizardLM/WizardLM-13B-V1.2',
                                                                               'lmsys/vicuna-13b-v1.5', 'allenai/tulu-2-13b', 'allenai/tulu-2-dpo-13b']},
               {'alligened':'lmsys/vicuna-13b-v1.3', 'target_model':['chavinlo/alpaca-13b','cognitivecomputations/WizardLM-13B-V1.0-Uncensored']}, 
               {'alligened':'lmsys/vicuna-33b-v1.3', 'target_model':['minlik/chinese-alpaca-33b-merged', 'cognitivecomputations/WizardLM-33B-V1.0-Uncensored']},
               {'alligened':'lmsys/vicuna-7b-v1.3', 'target_model':['chavinlo/alpaca-native', 'cognitivecomputations/WizardLM-7B-V1.0-Uncensored']},
               {'alligened':'mosaicml/mpt-7b-chat', 'target_model':['mosaicml/mpt-7b', 'mosaicml/mpt-7b-storywriter']},
               {'alligened':'mosaicml/mpt-30b-chat', 'target_model':['mosaicml/mpt-30b']},
               {'alligened':'tiiuae/falcon-7b-instruct', 'target_model':['tiiuae/falcon-7b','h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3', 'OpenAssistant/falcon-7b-sft-top1-696']},
               {'alligened':'tiiuae/falcon-40b-instruct', 'target_model':['tiiuae/falcon-40b', 'h2oai/h2ogpt-gm-oasst1-en-2048-falcon-40b-v2', 'OpenAssistant/falcon-40b-sft-top1-560']},
               {'alligened':'mistralai/Mistral-7B-Instruct-v0.2', 'target_model':['mistralai/Mistral-7B-v0.1', 'teknium/OpenHermes-2-Mistral-7B', 'NousResearch/Yarn-Mistral-7b-128k',
                                                                                  'Open-Orca/Mistral-7B-OpenOrca', 'teknium/OpenHermes-2.5-Mistral-7B',
                                                                                  'cognitivecomputations/dolphin-2.2.1-mistral-7b', 'openchat/openchat_3.5',
                                                                                  'berkeley-nest/Starling-LM-7B-alpha', 'HuggingFaceH4/zephyr-7b-alpha', 'cognitivecomputations/dolphin-2.6-mistral-7b-dpo',
                                                                                  'abhishekchohan/mistral-7B-forest-dpo']},
              {'alligened':'Qwen/Qwen-7B-Chat', 'target_model':['Qwen/Qwen-7B']},
              {'alligened':'Qwen/Qwen-14B-Chat', 'target_model':['Qwen/Qwen-14B']},
              {'alligened':'Qwen/Qwen1.5-0.5B-Chat', 'target_model':['Qwen/Qwen1.5-0.5B', 'RESMPDEV/Qwen1.5-Wukong-0.5B']},
              {'alligened':'Qwen/Qwen1.5-1.8B-Chat', 'target_model':['Qwen/Qwen1.5-1.8B']},
              {'alligened':'Qwen/Qwen1.5-4B-Chat', 'target_model':['Qwen/Qwen1.5-4B']},
              {'alligened':'Qwen/Qwen1.5-7B-Chat', 'target_model':['Qwen/Qwen1.5-7B']},
              {'alligened':'Qwen/Qwen1.5-14B-Chat', 'target_model':['Qwen/Qwen1.5-4B']},
              {'alligened':'01-ai/Yi-6B-Chat', 'target_model':['01-ai/Yi-6B']},
              {'alligened':'01-ai/Yi-34B-Chat', 'target_model':['01-ai/Yi-34B']},
              {'alligened':'deepseek-ai/deepseek-llm-7b-chat', 'target_model':['deepseek-ai/deepseek-llm-7b-base']},
              {'alligened':'deepseek-ai/deepseek-llm-16b-chat', 'target_model':['deepseek-ai/deepseek-llm-16b-base']},
              {'alligened':'google/gemma-7b-it', 'target_model':['google/gemma-7b', 'HuggingFaceH4/zephyr-7b-gemma-v0.1', 'CorticalStack/gemma-7b-ultrachat-sft'
                                                                 'macadeliccc/gemma-orchid-7b-dpo', 'mlabonne/Gemmalpaca-7B']},
              {'alligened':'google/gemma-2b-it', 'target_model':['google/gemma-2b','mlabonne/Gemmalpaca-2B', 'Syed-Hasan-8503/openhermes-gemma-2b-it']},
               ]
